apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: instavote
  source:
    path: prod
    repoURL: git@github.com:dmaxim/argo-labs.git
    targetRevision: prod-deploy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
